project:
  type: website
  output-dir: docs  # Changes the output folder from _site to docs/

website:
  title: "CEEE Assignments for Introduction to AI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Assignment1/assignment1_presentation.qmd
        text: Assignments1 Presentation
      - href: Assignment2/assignment2_presentation.qmd
        text: Assignments2 Presentation
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



